name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
      branches: [ main, master ]

jobs:
  build-and-scan:
    name: Build and Security Scan

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build mvn
        run: mvn -B clean install -DskipTests

      - name: Run SAST Scan (SpotBugs)
        run: mvn -B spotbugs:check

      - name: Run SCA (OWASP Dependency-Check)
        run: mvn -B dependency-check:check -Dnvd.api.key=${{ secrets.NVD_API_KEY }} -Danalyzer.ossindex.enabled=false

      - name: Upload OWASP Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-check-report
          path: target/dependency-check-report.html